// Copyright Parity Technologies (UK) Ltd.
// This file is part of Cumulus.

// Cumulus is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.

// Cumulus is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.

// You should have received a copy of the GNU General Public License
// along with Cumulus.  If not, see <http://www.gnu.org/licenses/>.

//! Autogenerated weights for `pallet_bridge_transfer`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2023-03-30, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `bm3`, CPU: `Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("westmint-dev"), DB CACHE: 1024

// Executed Command:
// target/production/polkadot-parachain
// benchmark
// pallet
// --steps=50
// --repeat=20
// --extrinsic=*
// --execution=wasm
// --wasm-execution=compiled
// --heap-pages=4096
// --json-file=/var/lib/gitlab-runner/builds/zyw4fam_/0/parity/mirrors/cumulus/.git/.artifacts/bench.json
// --pallet=pallet_bridge_transfer
// --chain=westmint-dev
// --header=./file_header.txt
// --output=./parachains/runtimes/assets/westmint/src/weights/

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::Weight};
use sp_std::marker::PhantomData;

/// Weight functions for `pallet_bridge_transfer`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> pallet_bridge_transfer::WeightInfo for WeightInfo<T> {
	fn transfer_asset_via_bridge() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 0_000 picoseconds.
		Weight::from_parts(0, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
	fn ping_via_bridge() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 0_000 picoseconds.
		Weight::from_parts(0, 0)
			.saturating_add(Weight::from_parts(0, 0))
	}
	/// Storage: BridgeTransfer AllowedExporters (r:1 w:1)
	/// Proof: BridgeTransfer AllowedExporters (max_values: None, max_size: Some(2537), added: 5012, mode: MaxEncodedLen)
	/// Storage: ParachainInfo ParachainId (r:1 w:0)
	/// Proof: ParachainInfo ParachainId (max_values: Some(1), max_size: Some(4), added: 499, mode: MaxEncodedLen)
	fn add_exporter_config() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `109`
		//  Estimated: `7491`
		// Minimum execution time: 15_704_000 picoseconds.
		Weight::from_parts(16_139_000, 0)
			.saturating_add(Weight::from_parts(0, 7491))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: BridgeTransfer AllowedExporters (r:1 w:1)
	/// Proof: BridgeTransfer AllowedExporters (max_values: None, max_size: Some(2537), added: 5012, mode: MaxEncodedLen)
	fn remove_exporter_config() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `165`
		//  Estimated: `6002`
		// Minimum execution time: 13_749_000 picoseconds.
		Weight::from_parts(14_178_000, 0)
			.saturating_add(Weight::from_parts(0, 6002))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: BridgeTransfer AllowedExporters (r:1 w:1)
	/// Proof: BridgeTransfer AllowedExporters (max_values: None, max_size: Some(2537), added: 5012, mode: MaxEncodedLen)
	fn update_exporter_config() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `165`
		//  Estimated: `6002`
		// Minimum execution time: 18_664_000 picoseconds.
		Weight::from_parts(18_982_000, 0)
			.saturating_add(Weight::from_parts(0, 6002))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}

	fn update_bridged_target_location() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `109`
		//  Estimated: `5884`
		// Minimum execution time: 12_859_000 picoseconds.
		Weight::from_parts(19_737_000, 0)
			.saturating_add(Weight::from_parts(0, 5884))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}

	fn remove_bridged_target_location() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `109`
		//  Estimated: `5884`
		// Minimum execution time: 12_859_000 picoseconds.
		Weight::from_parts(19_737_000, 0)
			.saturating_add(Weight::from_parts(0, 5884))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}

	fn allow_reserve_asset_transfer_for() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `109`
		//  Estimated: `5884`
		// Minimum execution time: 12_859_000 picoseconds.
		Weight::from_parts(19_737_000, 0)
			.saturating_add(Weight::from_parts(0, 5884))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}

	fn disallow_reserve_asset_transfer_for() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `109`
		//  Estimated: `5884`
		// Minimum execution time: 12_859_000 picoseconds.
		Weight::from_parts(19_737_000, 0)
			.saturating_add(Weight::from_parts(0, 5884))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}

	/// Storage: BridgeTransfer AllowedUniversalAliases (r:1 w:1)
	/// Proof: BridgeTransfer AllowedUniversalAliases (max_values: None, max_size: Some(2419), added: 4894, mode: MaxEncodedLen)
	fn add_universal_alias() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `109`
		//  Estimated: `5884`
		// Minimum execution time: 12_859_000 picoseconds.
		Weight::from_parts(19_737_000, 0)
			.saturating_add(Weight::from_parts(0, 5884))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: BridgeTransfer AllowedUniversalAliases (r:1 w:1)
	/// Proof: BridgeTransfer AllowedUniversalAliases (max_values: None, max_size: Some(2419), added: 4894, mode: MaxEncodedLen)
	fn remove_universal_alias() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `158`
		//  Estimated: `5884`
		// Minimum execution time: 15_939_000 picoseconds.
		Weight::from_parts(16_245_000, 0)
			.saturating_add(Weight::from_parts(0, 5884))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: BridgeTransfer AllowedReserveLocations (r:1 w:1)
	/// Proof: BridgeTransfer AllowedReserveLocations (max_values: Some(1), max_size: Some(4817), added: 5312, mode: MaxEncodedLen)
	fn add_reserve_location() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `109`
		//  Estimated: `6302`
		// Minimum execution time: 12_764_000 picoseconds.
		Weight::from_parts(13_060_000, 0)
			.saturating_add(Weight::from_parts(0, 6302))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: BridgeTransfer AllowedReserveLocations (r:1 w:1)
	/// Proof: BridgeTransfer AllowedReserveLocations (max_values: Some(1), max_size: Some(4817), added: 5312, mode: MaxEncodedLen)
	fn remove_reserve_location() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `141`
		//  Estimated: `6302`
		// Minimum execution time: 14_613_000 picoseconds.
		Weight::from_parts(14_927_000, 0)
			.saturating_add(Weight::from_parts(0, 6302))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
}
