{
 "title": "BridgeHubRococo <> BridgeHubWococo maintenance (00000001)",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Relay build commit",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "substrate_relay_build_info{domain=\"parity-testnet\"}",
     "legendFormat": "{{commit}}"
    }
   ]
  },
  {
   "title": "Relay build version",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "substrate_relay_build_info{domain=\"parity-testnet\"}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Relay errors/warnings per minute",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 10, "y": 0 },
   "targets": [
    {
     "expr": "count_over_time({container=\"bridges-common-relay\"} |~ `(?i)(warn|error|fail)` [1m])",
     "legendFormat": "Errors per minute"
    }
   ]
  },
  {
   "title": "Rococo headers mismatch",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "Rococo_to_BridgeHubWococo_Sync_is_source_and_source_at_target_using_different_forks{domain=\"parity-testnet\"}",
     "legendFormat": "Best BridgeHubRococo header at BridgeHubWococo doesn't match the same header of BridgeHubRococo"
    }
   ]
  },
  {
   "title": "Wococo headers mismatch",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 9, "y": 5 },
   "targets": [
    {
     "expr": "Wococo_to_BridgeHubRococo_Sync_is_source_and_source_at_target_using_different_forks{domain=\"parity-testnet\"}",
     "legendFormat": "Best BridgeHubRococo header at BridgeHubWococo doesn't match the same header of BridgeHubRococo"
    }
   ]
  },
  {
   "title": "BridgeHubRococo headers mismatch",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "BridgeHubRococo_to_BridgeHubWococo_MessageLane_00000001_is_source_and_source_at_target_using_different_forks{domain=\"parity-testnet\"}",
     "legendFormat": "Best BridgeHubRococo header at BridgeHubWococo doesn't match the same header of BridgeHubRococo"
    }
   ]
  },
  {
   "title": "BridgeHubWococo headers mismatch",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 9, "y": 12 },
   "targets": [
    {
     "expr": "BridgeHubWococo_to_BridgeHubRococo_MessageLane_00000001_is_source_and_source_at_target_using_different_forks{domain=\"parity-testnet\"}",
     "legendFormat": "Best BridgeHubRococo header at BridgeHubWococo doesn't match the same header of BridgeHubRococo"
    }
   ]
  },
  {
   "title": "Relay balances at RococoBridgeHub",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "at_BridgeHubRococo_relay_BridgeHubWococoMessages_balance{domain=\"parity-testnet\"}",
     "legendFormat": "Messages Relay Balance"
    },
    {
     "expr": "at_BridgeHubRococo_relay_WococoHeaders_reward_for_msgs_to_BridgeHubWococo_on_lane_00000001{domain=\"parity-testnet\"} + at_BridgeHubRococo_relay_BridgeHubWococoMessages_reward_for_msgs_to_BridgeHubWococo_on_lane_00000001{domain=\"parity-testnet\"}",
     "legendFormat": "Pending reward"
    }
   ]
  },
  {
   "title": "Relay balances at WococoBridgeHub",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 19 },
   "targets": [
    {
     "expr": "at_BridgeHubWococo_relay_BridgeHubRococoMessages_balance{domain=\"parity-testnet\"}",
     "legendFormat": "Messages Relay Balance"
    },
    {
     "expr": "at_BridgeHubRococo_relay_BridgeHubWococoMessages_reward_for_msgs_from_BridgeHubWococo_on_lane_00000001{domain=\"parity-testnet\"} + at_BridgeHubRococo_relay_BridgeHubWococoMessages_reward_for_msgs_to_BridgeHubWococo_on_lane_00000001{domain=\"parity-testnet\"}",
     "legendFormat": "Pending reward"
    }
   ]
  }
 ]
}