# frozen_string_literal: true

source 'https://rubygems.org'

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

gem 'octokit', '~> 4'

gem 'git_diff_parser', '~> 3'

gem 'rake', group: :dev

gem 'test-unit', group: :dev

gem 'optparse', '~> 0.1.1'

gem 'logger', '~> 1.4'

gem 'rubocop', group: :dev, require: false
