{
 "title": "Rialto+Millau maintenance dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Rialto: storage proof overhead",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rialto_storage_proof_overhead{instance='relay-millau-rialto:9616'}",
     "legendFormat": "Actual overhead"
    },
    { "expr": "1024", "legendFormat": "At runtime (hardcoded)" }
   ]
  },
  {
   "title": "Millau: Rialto -> Millau conversion rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "polkadot_to_base_conversion_rate{instance='relay-millau-rialto:9616'} / kusama_to_base_conversion_rate{instance='relay-millau-rialto:9616'}",
     "legendFormat": "Outside of runtime (actually Polkadot -> Kusama)"
    },
    {
     "expr": "Millau_Rialto_to_Millau_conversion_rate{instance='relay-millau-rialto:9616'}",
     "legendFormat": "At runtime"
    }
   ]
  },
  {
   "title": "Millau: storage proof overhead",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "millau_storage_proof_overhead{instance='relay-millau-rialto:9616'}",
     "legendFormat": "Actual overhead"
    },
    { "expr": "1024", "legendFormat": "At runtime (hardcoded)" }
   ]
  },
  {
   "title": "Rialto: Millau -> Rialto conversion rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kusama_to_base_conversion_rate{instance='relay-millau-rialto:9616'} / polkadot_to_base_conversion_rate{instance='relay-millau-rialto:9616'}",
     "legendFormat": "Outside of runtime (actually Kusama -> Polkadot)"
    },
    {
     "expr": "Rialto_Millau_to_Rialto_conversion_rate{instance='relay-millau-rialto:9616'}",
     "legendFormat": "At runtime"
    }
   ]
  },
  {
   "title": "Rialto relay balances",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "at_Rialto_relay_MillauHeaders_balance",
     "legendFormat": "With-Millau headers relay account balance"
    },
    {
     "expr": "at_Rialto_relay_MillauMessages_balance",
     "legendFormat": "With-Millau messages relay account balance"
    },
    {
     "expr": "at_Rialto_relay_MillauMessagesPalletOwner_balance",
     "legendFormat": "With-Millau messages pallet owner account balance"
    }
   ]
  },
  {
   "title": "Millau relay balances",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "at_Millau_relay_RialtoHeaders_balance{instance=\"relay-millau-rialto:9616\"}",
     "legendFormat": "With-Rialto headers relay account balance"
    },
    {
     "expr": "at_Millau_relay_RialtoMessages_balance",
     "legendFormat": "With-Rialto messages relay account balance"
    },
    {
     "expr": "at_Millau_relay_RialtoMessagesPalletOwner_balance",
     "legendFormat": "With-Rialto messages pallet owner account balance"
    }
   ]
  },
  {
   "title": "Whether with-Rialto-grandpa-pallet and Rialto itself are on different forks",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "Rialto_to_Millau_MessageLane_00000000_is_source_and_source_at_target_using_different_forks OR on() vector(0)",
     "legendFormat": "On different forks?"
    }
   ]
  },
  {
   "title": "Whether with-Millau-grandpa-pallet and Millau itself are on different forks",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "Millau_to_Rialto_MessageLane_00000000_is_source_and_source_at_target_using_different_forks OR on() vector(0)",
     "legendFormat": "On different forks?"
    }
   ]
  },
  {
   "title": "Count of unprofitable message delivery transactions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "Millau_to_Rialto_MessageLane_00000000_unprofitable_delivery_transactions",
     "legendFormat": "Millau -> Rialto, lane 00000000"
    },
    {
     "expr": "Rialto_to_Millau_MessageLane_00000000_unprofitable_delivery_transactions",
     "legendFormat": "Rialto -> Millau, lane 00000000"
    }
   ]
  }
 ]
}