(function() {var implementors = {
"asset_hub_kusama_runtime":[["impl Config for <a class=\"struct\" href=\"asset_hub_kusama_runtime/xcm_config/struct.XcmConfig.html\" title=\"struct asset_hub_kusama_runtime::xcm_config::XcmConfig\">XcmConfig</a>"]],
"asset_hub_polkadot_runtime":[["impl Config for <a class=\"struct\" href=\"asset_hub_polkadot_runtime/xcm_config/struct.XcmConfig.html\" title=\"struct asset_hub_polkadot_runtime::xcm_config::XcmConfig\">XcmConfig</a>"]],
"asset_hub_westend_runtime":[["impl Config for <a class=\"struct\" href=\"asset_hub_westend_runtime/xcm_config/struct.XcmConfig.html\" title=\"struct asset_hub_westend_runtime::xcm_config::XcmConfig\">XcmConfig</a>"]],
"bridge_hub_kusama_runtime":[["impl Config for <a class=\"struct\" href=\"bridge_hub_kusama_runtime/xcm_config/struct.XcmConfig.html\" title=\"struct bridge_hub_kusama_runtime::xcm_config::XcmConfig\">XcmConfig</a>"]],
"bridge_hub_polkadot_runtime":[["impl Config for <a class=\"struct\" href=\"bridge_hub_polkadot_runtime/xcm_config/struct.XcmConfig.html\" title=\"struct bridge_hub_polkadot_runtime::xcm_config::XcmConfig\">XcmConfig</a>"]],
"bridge_hub_rococo_runtime":[["impl Config for <a class=\"struct\" href=\"bridge_hub_rococo_runtime/xcm_config/struct.XcmConfig.html\" title=\"struct bridge_hub_rococo_runtime::xcm_config::XcmConfig\">XcmConfig</a>"]],
"collectives_polkadot_runtime":[["impl Config for <a class=\"struct\" href=\"collectives_polkadot_runtime/xcm_config/struct.XcmConfig.html\" title=\"struct collectives_polkadot_runtime::xcm_config::XcmConfig\">XcmConfig</a>"]],
"glutton_runtime":[["impl Config for <a class=\"struct\" href=\"glutton_runtime/xcm_config/struct.XcmConfig.html\" title=\"struct glutton_runtime::xcm_config::XcmConfig\">XcmConfig</a>"]],
"parachain_template_runtime":[["impl Config for <a class=\"struct\" href=\"parachain_template_runtime/xcm_config/struct.XcmConfig.html\" title=\"struct parachain_template_runtime::xcm_config::XcmConfig\">XcmConfig</a>"]],
"penpal_runtime":[["impl Config for <a class=\"struct\" href=\"penpal_runtime/xcm_config/struct.XcmConfig.html\" title=\"struct penpal_runtime::xcm_config::XcmConfig\">XcmConfig</a>"]],
"rococo_parachain_runtime":[["impl Config for <a class=\"struct\" href=\"rococo_parachain_runtime/struct.XcmConfig.html\" title=\"struct rococo_parachain_runtime::XcmConfig\">XcmConfig</a>"]],
"shell_runtime":[["impl Config for <a class=\"struct\" href=\"shell_runtime/xcm_config/struct.XcmConfig.html\" title=\"struct shell_runtime::xcm_config::XcmConfig\">XcmConfig</a>"]]
};if (window.register_implementors) {window.register_implementors(implementors);} else {window.pending_implementors = implementors;}})()