{
 "title": "RialtoParachain+Millau maintenance dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "RialtoParachain relay balances",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "at_RialtoParachain_relay_MillauHeaders_balance{instance=\"relay-millau-rialto-parachain-1:9616\"}",
     "legendFormat": "With-Millau headers relay account balance"
    },
    {
     "expr": "at_RialtoParachain_relay_MillauMessages_balance{instance=\"relay-millau-rialto-parachain-1:9616\"}",
     "legendFormat": "With-Millau messages relay account balance"
    },
    {
     "expr": "at_RialtoParachain_relay_MillauMessagesPalletOwner_balance{instance=\"relay-millau-rialto-parachain-1:9616\"}",
     "legendFormat": "With-Millau messages pallet owner account balance"
    }
   ]
  },
  {
   "title": "Millau relay balances",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "at_Millau_relay_RialtoHeaders_balance{instance=\"relay-millau-rialto-parachain-1:9616\"}",
     "legendFormat": "With-Rialto headers relay account balance"
    },
    {
     "expr": "at_Millau_relay_RialtoParachainMessages_balance{instance=\"relay-millau-rialto-parachain-1:9616\"}",
     "legendFormat": "With-RialtoParachain messages relay account balance"
    },
    {
     "expr": "at_Millau_relay_RialtoParachains_balance{instance=\"relay-millau-rialto-parachain-1:9616\"}",
     "legendFormat": "With-Rialto parachains relay account balance"
    },
    {
     "expr": "at_Millau_relay_RialtoParachainMessagesPalletOwner_balance{instance=\"relay-millau-rialto-parachain-1:9616\"}",
     "legendFormat": "With-RialtoParachain messages pallet owner account balance"
    }
   ]
  },
  {
   "title": "Whether with-RialtoParachain-parachains-pallet and RialtoParachain itself are on different forks",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "RialtoParachain_to_Millau_MessageLane_00000000_is_source_and_source_at_target_using_different_forks{instance=\"relay-millau-rialto-parachain-1:9616\"} OR on() vector(0)",
     "legendFormat": "On different forks?"
    }
   ]
  },
  {
   "title": "Whether with-Millau-grandpa-pallet and Millau itself are on different forks",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "Millau_to_RialtoParachain_MessageLane_00000000_is_source_and_source_at_target_using_different_forks{instance=\"relay-millau-rialto-parachain-1:9616\"} OR on() vector(0)",
     "legendFormat": "On different forks?"
    }
   ]
  }
 ]
}